ARDUINO_DIR = $(HOME)/.arduino_ide
ARDUINO_LIBS = Adafruit_GFX_Library Adafruit_PCD8544_Nokia_5110_LCD_library \
			   arduino-menusystem SPI
ARDMK_DIR = $(HOME)/.arduino_mk
BOARD_TAG = uno

CXXFLAGS_STD += -std=gnu++11

include $(ARDMK_DIR)/Arduino.mk
